---
title: "Differential Analyis and Clustering of H3K27ac ChIPseq data of Cohesin AMLs"
author: "Alexander Fischer"
date: "04 2022"
output: html
---

# Load libraries and data
```{r}
#libraries
library(edgeR)
library(cqn)
library(scales)
library(ggplot2)
library(umap)
library(ggrepel)
library(umap)
library(ggplot2)
library(ggrepel)
library(cowplot)
#paths
WORKDIR<-"/misc/data/analysis/project_cohesin/CD34/ChIP_KD_analysis/H3K27ac"
DIFFPEAKS<-file.path(WORKDIR,"diffPeaks")
FIGDIR<-file.path(WORKDIR,"figures")
dir.create(file.path(FIGDIR,"Clustering"))
#data and group vectors 
data <- read.delim(file.path(WORKDIR,"mergedCD34_H3K27ac.CD34.ann.table.txt"), row.names="ID")
covar <- read.delim(file.path(WORKDIR,"peaks","mergedCD34_H3K27ac.filtered.peaks.CpGann.txt"), row.names="ID") #cpg and leght annotaded peaks
group <- factor(c(rep("CTRL",10), rep("SA1KD",5), rep("SA2KD",6), rep("RAD21KD",4)))
batch <- factor(c(14,14,17,18,19,21,22,27,28,24,14,17,21,27,28,14,17,20,21,22,28,18,22,27,28))
metadata<-data.frame(group,batch)
row.names(metadata)<-colnames(data)

#prepare peak inforamtion for annotation of results tables
peaks <- read.delim(file.path(WORKDIR,"peaks","mergedCD34_H3K27ac.filtered.peaks.refChr.txt"), header=T)
colnames(peaks) <- c("ID","chr","start","stop","strand","NA")
allpositions <- peaks[,-1]
rownames(allpositions) <- peaks[,1]
allpositions <- allpositions[,-(6:11)]
```

# cqn normalization
```{r}
# create a dgelist object, filter out very rare peaks
d <- DGEList(counts=data,group=group)
colnames(d) <- c("14_CTRL","14_MOCK","17_CTRL","18_CTRL","19_CTRL","21_CTRL","22_CTRL","27_CTRL","28_CTRL","24_CTRL","14_SA1KD","17_SA1KD","21_SA1KD","27_SA1KD","28_SA1KD","14_SA2KD","17_SA2KD","20_SA2KD","21_SA2KD","22_SA2KD","28_SA2KD","18_RAD21KD","22_RAD21KD","27_RAD21KD","28_RAD21KD")
keep <- rowSums(cpm(d) > 1) >= 3
summary(keep)
d <- d[keep, , keep.lib.sizes=FALSE]
# merge covariates (Peak info) and counts
covar.merged <- merge(d$counts, covar, by="row.names")
cov <- covar.merged [,27:28]
head(cov)
rownames(cov) <- covar.merged [,1]
counts <- data.matrix(covar.merged [,2:26])
rownames(counts) <- covar.merged [,1]
stopifnot(all(rownames(counts) == rownames(cov)))

# run cqn using lenth and gc content of the samples
cqn.d <- cqn(counts, lengths = cov$length, x = cov$gccontent, tau = 0.95, verbose = TRUE)
# cqn plot:
pdf(file=file.path(FIGDIR,"cqn.qc.mergedCD34.pdf"), height=4, width=8)
par(mfrow=c(1,2))
cqnplot(cqn.d, n = 1, xlab = "GC content", lty = 1, ylim = c(1,10))
cqnplot(cqn.d, n = 2, xlab = "length", lty = 1, ylim = c(1,10))
dev.off()

# create new DEG object implementing the offset
y <- DGEList(counts=counts,group=group)
design <- model.matrix(~0 + group)
rownames(design) <- colnames(y)
offset <- cqn.d$glm.offset
y <- scaleOffset(y, offset)
logcpm <- cpm(y, prior.count=2, log=TRUE, offset=y$offset)

#remove the donor batch effect from counts (used for visualization only)
corr.logcpm <- removeBatchEffect(logcpm, batch=batch, design=design)
write.table (corr.logcpm, file = file.path(WORKDIR,"mergedCD34_H3K27ac_ReadCountTable.norm.corr.logcpm.txt"), sep = "\t", col.names=NA, quote=FALSE)
```


# Clusteting of normalized counts
```{r}
set.seed(seed = 1234)
 umap.dat<-umap::umap(t(as.matrix(corr.logcpm))) #35564
  #appply umap algorithm on transposed data matrix, then extract layout for plotting
  umap.dat<-data.frame(umap.dat$layout) 
  umap.dat$group<-factor(group,levels=c("CTRL","SA2KD","SA1KD","RAD21KD"))
  umap.dat$Donor<-factor(metadata$batch)
  umap.dat$Donorgroup<-paste0(umap.dat$group,"_",umap.dat$batch)
#generate ggplot object: here showing NPM1
  umap.p<-ggplot(data = umap.dat)+
    aes(x = X1, y = X2)+
    xlab("UMAP2") +
    ylab("UMAP1") +
    scale_x_continuous(limits = c(-2.5,2.5)) +
    scale_y_continuous(limits = c(-2.5,2.5))+
    geom_point(size = 12, aes(colour=group))+
    scale_color_manual(values = c("CTRL" = "firebrick", "SA2KD" = "seagreen", "SA1KD" = "darkgoldenrod","RAD21KD"="mediumvioletred"),labels=c("CTRL-HSPCs","STAG2KD","STAG1KD","RAD21KD")) +
    geom_text_repel(aes(label=Donor),size=4,segment.size=0.2,min.segment.length=0.0,point.padding=.05,segment.alpha=0.5,max.overlaps = 50,force = 50, show.legend = FALSE) +
    labs(title = "UMAP H3K27ac CD34 HPSCs")+
    theme_light(base_size=12) +
    theme(plot.tag=element_text(size = 12*2.0, face = "bold"),
          plot.title = element_text(size = 12, face = "bold"),
          plot.title.position = "panel",
          legend.text = element_text(colour="black", size = 12, face = "plain"),
          legend.title = element_text(colour="black", size = 12, face = "bold"),
          legend.box.just = "top",
          axis.text = element_text(colour = "black", size = 12, face = "plain"),
          axis.title = element_text(colour = "black",size = 12,face = "plain"),
          panel.grid = element_blank(),
          panel.border = element_rect(colour = "black",size=2),
          axis.ticks = element_line(colour="black"),
          aspect.ratio = 1.0, #plot panel aspect ratio for squared == 1.0! :)
          legend.position = "right"
        )
pdf(file= file.path(FIGDIR,"Clustering","UMAP_H3K27ac.donorlab.edgeR.corr.pdf"), height=8, width=12)
plot(umap.p) 
dev.off() 
```

# Differnetial peak analysis
```{r}
# estimate dispersion of cqn dGElist object and fit
design <- model.matrix(~0 + group + batch) #design including batch!
y.cqn <- estimateDisp(y, design, robust=TRUE)
y.cqn
fit <- glmQLFit(y.cqn, design)

# RAD21 KD vs CTRL with cqn norm
con <- makeContrasts(groupRAD21KD-groupCTRL, levels=design)
qlf <- glmQLFTest(fit, contrast=con)
qstat.cqn.RAD21 <- topTags(qlf, n=Inf)
write.table (qstat.cqn.RAD21, file = file.path(DIFFPEAKS,"qstat.RAD21KDvsCTRL.upperQ0.95.cqn.CD34.txt"), sep = "\t", col.names=NA, quote=FALSE)
summary(qdt <- decideTestsDGE(qlf, lfc=1))
# MvA plot 
pdf(file=file.path(WORKDIR,"figures","edgeR_H3K27ac_MvA_cqn_RAD21KDvsCTRL.pdf"), height=5, width=5)
plotMD(qlf, status=qdt , values=c(1,-1), hl.col = c("red","blue"), hl.cex = 0.6, bg.col="gray", main="H3K27ac MvA KD vs CTRL")
abline(h=c(-1,1), col="black")
dev.off()

# SA1 KD vs CTRL with cqn norm
con <- makeContrasts(groupSA1KD-groupCTRL, levels=design)
qlf <- glmQLFTest(fit, contrast=con)
qstat.cqn.SA1 <- topTags(qlf, n=Inf)
write.table (qstat.cqn.SA1 , file = file.path(DIFFPEAKS,"qstat.SA1KDvsCTRL.upperQ0.95.cqn.CD34.txt"), sep = "\t", col.names=NA, quote=FALSE)
summary(qdt <- decideTestsDGE(qlf, lfc=1))
# MvA plot 
pdf(file=file.path(WORKDIR,"figures","edgeR_H3K27ac_MvA_cqn_SA1KDvsCTRL.pdf"), height=5, width=5)
plotMD(qlf, status=qdt , values=c(1,-1), hl.col = c("red","blue"), hl.cex = 0.6, bg.col="gray", main="H3K27ac MvA KD vs CTRL")
abline(h=c(-1,1), col="black")
dev.off()
# SA2 KD vs CTRL with cqn norm
con <- makeContrasts(groupSA2KD-groupCTRL, levels=design)
qlf <- glmQLFTest(fit, contrast=con)
qstat.cqn.SA2  <- topTags(qlf, n=Inf)
write.table (qstat.cqn.SA2 , file = file.path(DIFFPEAKS,"qstat.SA2KDvsCTRL.upperQ0.95.cqn.CD34.txt"), sep = "\t", col.names=NA, quote=FALSE)
summary(qdt <- decideTestsDGE(qlf, lfc=1))
#       -1*groupCTRL 1*groupSA2KD
#Down                          57
#NotSig                     35419
#Up                            88
# MvA plot 
pdf(file=file.path(WORKDIR,"figures","edgeR_H3K27ac_MvA_cqn_SA2KDvsCTRL.pdf"), height=5, width=5)
plotMD(qlf, status=qdt , values=c(1,-1), hl.col = c("red","blue"), hl.cex = 0.6, bg.col="gray", main="H3K27ac MvA KD vs CTRL")
abline(h=c(-1,1), col="black")
dev.off()
```

# filter results
```{r}
qstatlist<-list(qstat.cqn.RAD21,qstat.cqn.SA1,qstat.cqn.SA2)
names(qstatlist)<-c("qstat.upperQ0.95.cqn.RAD21","qstat.upperQ0.95.cqn.SA1","qstat.upperQ0.95.cqn.SA2")
KDs<-c("SA1","SA2","RAD21")
for (KD in KDs){
qstatlist[[paste0("qstat.",KD,"KDvsCTRL.upperQ0.95.cqn.2foldUp")]]<-subset(qstatlist[[paste0("qstat.upperQ0.95.cqn.",KD)]]$table, logFC > 1 & logCPM > 1 & FDR < .05)
qstatlist[[paste0("qstat.",KD,"KDvsCTRL.upperQ0.95.cqn.2foldDown")]]<-subset(qstatlist[[paste0("qstat.upperQ0.95.cqn.",KD)]]$table, logFC < (-1) & logCPM > 1 & FDR < .05)
qstatlist[[paste0("qstat.",KD,"KDvsCTRL.upperQ0.95.cqn.2foldUp.CPM05")]]<-subset(qstatlist[[paste0("qstat.upperQ0.95.cqn.",KD)]]$table, logFC > 1 & logCPM > 0.585 & FDR < .05)
qstatlist[[paste0("qstat.",KD,"KDvsCTRL.upperQ0.95.cqn.2foldDown.CPM05")]]<-subset(qstatlist[[paste0("qstat.upperQ0.95.cqn.",KD)]]$table, logFC < (-1) & logCPM > 0.585 & FDR < .05)
qstatlist[[paste0("qstat.",KD,"KDvsCTRL.upperQ0.95.cqn.1foldUp")]]<-subset(qstatlist[[paste0("qstat.upperQ0.95.cqn.",KD)]]$table, logFC > 0.585 & logCPM > 1 & FDR < .05)
qstatlist[[paste0("qstat.",KD,"KDvsCTRL.upperQ0.95.cqn.1foldDown")]]<-subset(qstatlist[[paste0("qstat.upperQ0.95.cqn.",KD)]]$table, logFC < (-0.585) & logCPM > 1 & FDR < .05)
qstatlist[[paste0("qstat.",KD,"KDvsCTRL.upperQ0.95.cqn.1foldUp.CPM05")]]<-subset(qstatlist[[paste0("qstat.upperQ0.95.cqn.",KD)]]$table, logFC > 0.585 & logCPM > 0.585 & FDR < .05)
qstatlist[[paste0("qstat.",KD,"KDvsCTRL.upperQ0.95.cqn.1foldDown.CPM05")]]<-subset(qstatlist[[paste0("qstat.upperQ0.95.cqn.",KD)]]$table, logFC < (-0.585) & logCPM > 0.585 & FDR < .05)
}

# count diffpeaks
filts2<-c("2foldUp","2foldDown","1foldUp","1foldDown","2foldUp.CPM05","2foldDown.CPM05","1foldUp.CPM05","1foldDown.CPM05")
RESDF<-data.frame()
for (KD in KDs){
            for (filt in filts2){
RESDF[filt,KD]<-nrow(qstatlist[[paste0("qstat.",KD,"KDvsCTRL.upperQ0.95.cqn.",filt)]])
}}
RESDF
write.table(RESDF,file.path(WORKDIR,"diffPeaks","edgeR_H3K27ac_diffpeak_summary.CD34.txt"),sep="\t",quote=FALSE)

# merge with results with peak pos and write filtered result tables
for (KD in KDs){
            for (filt in filts2){
diffpos<-merge(allpositions,qstatlist[[paste0("qstat.",KD,"KDvsCTRL.upperQ0.95.cqn.",filt)]], by="row.names")
write.table(diffpos, file = file.path(WORKDIR,"diffPeaks",paste0("qstat.",KD,"KDvsCTRL.upperQ0.95.cqn.",filt,".CD34.txt")), sep = "\t", row.names=F, quote=FALSE)
}}
```

